### ISSUE TITLE
Something that can benefit your VFP versioning on GitHub

### ISSUE THREAD

**Issue by fdbozzo** [arquimedescrivelari/foxpages#1]
Hi Arquimedes!

I think that your project may benefit of FoxBin2Prg for the binaries (It's a VFPx bi-directional conversor for VFP 9).
https://github.com/fdbozzo/foxbin2prg/wiki

By the way, you have a great project, I will give it a try when I get some free time.

Best Regards!

Fernando D. Bozzo

**Comment by arquimedescrivelari** [comment]
Hi Fernando,

Great project too! I'm not sure how to use it with FPS, because all source code is in prg files, but it should definitely be very useful for other projects I have.

Thank you!

Arquimedes Crivelari
