### ISSUE TITLE
Installation on third party webhosting servers

### ISSUE THREAD

**Issue by vfpindia** [arquimedescrivelari/foxpages#2]
How can we use this "Foxpages"  using third party webhosting.
if yes : suggest some sites fulfill requirement for it.
because it is very hard to setup 24x7 dedicated server for it in normal case.

**Comment by arquimedescrivelari** [comment]
I presume your are talking about your own dedicated server. I agree that might be hard to find a good ISP, setup a server, DNS, Reverse DNS, Routers, Firewalls, Digital Certificates, Email server, Antivirus, SPAM Filters, Blocklists and of course Backup System...

In this case you can start with a Virtual Private Server (VPS) like this:
https://www.godaddy.com/hosting/windows-vps?isc=hosstbr02

Or a with a Dedicate Server like this:
https://www.godaddy.com/hosting/windows-dedicated-server?isc=hosstbr02

This was only examples, there are many hosting companies on the internet.

Some tips:

1) Find good reputation hosting company.

2) Find the datacenter with lowest latency to your customers.

3) You'll need support to setup your server.

Regards,

Arquimedes Crivelari
